#! /bin/sh
ipaddr="`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -n 1`"
docker run \
    --publish 8081:8081 \
    --publish 10251-10254:10251-10254 \
    --memory 2g --cpus=2.0 \
    --name=cosmosdb \
    --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3 \
    --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
    --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=$ipaddr \
    --interactive \
    --tty \
    --rm \
    mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator