name: Equipper

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Stage Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Unit Test
        run: dotnet test UnitTest/UnitTest.csproj --no-restore --verbosity normal
      - name: Strava API Test
        run: dotnet test StravaApiTest/StravaApiTest.csproj --no-restore --verbosity normal
      - name: Cosmos Test WILL FAIL
        run: dotnet test CosmosStorageTest/CosmosStorageTest.csproj --no-restore --verbosity normal
      - name: Build And Stage
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_OCEAN_0A357FA0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/Website" # App source code path
          api_location: "/FunctionApp" # Api source code path - optional
          output_location: ".github/workflows" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Deploy To Prod Job
    steps:
      - name: Deploy To Prod
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_OCEAN_0A357FA0F }}
          action: "close"
