name: Unit and Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  test_job: 
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: windows-latest
    name: Test Job
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - uses: southpolesteve/cosmos-emulator-github-action@v1
      - name: Setup .NET 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Unit Test
        run: dotnet test UnitTest/UnitTest.csproj --no-restore --verbosity normal
      - name: Strava API Test
        run: dotnet test StravaApiTest/StravaApiTest.csproj --no-restore --verbosity normal
      - name: Cosmos Test
        run: dotnet test CosmosStorageTest/CosmosStorageTest.csproj --no-restore --verbosity normal
