name: Lighthouse

on:
  workflow_dispatch:
    inputs:
        site_url:
          description: 'Site URL'
          required: true
          default: 'https://equipper.bencoomes.com'
          type: string

jobs:
  run-lighthouse-check-job:
    runs-on: ubuntu-latest
    name: Run Lighthouse Check
    steps:
      - name: Lighthouse Audit
        uses: jakejarvis/lighthouse-action@a3bcc9973b3ce65beff316b3cac53b92e58dcc12
        with:
          url: ${{inputs.site_url}}
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouseReport
          path: './report'
